# Generated by Django 3.0.5 on 2020-04-20 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0002_auto_20200420_1015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='titleman',
            new_name='title',
        ),
    ]
